---
title: "Week 9 - Intro to Lidar Data: Part II"
author: "Asad Waseem"
date: "15-08-2026"

format:
  html:
    toc: true
    toc-depth: 6
    toc-location: left
    code-fold: true
---

# Contents

Last week you got familiar with the principles of lidar sensors and the use of the data.

This week you will continue working with these data. You will work with two las-files from Grunewald. The one you already used and another which is located in the vicinity. Additionally, you will make use of the forestry data provided via fisbroker (we already used that one).

---

# 1. Lidar data - Tutorial
The detailed tutorial for the lidR package can be found here: [https://r-lidar.github.io/lidRbook/](https://r-lidar.github.io/lidRbook/)

---


# 2. The Data

The data of this week can be found here: [https://box.fu-berlin.de/s/xXJ5retoYgR64EY](https://box.fu-berlin.de/s/xXJ5retoYgR64EY)

Detailed information of the attributes of the vector data can be found at Geodatensuche (sorry, only in German): (search for “Alters- und Bestandesstruktur der Wälder” of 2014) [https://gdi.berlin.de/geonetwork/srv/ger/catalog.search#/metadata/ea216e7d-77ca-3f96-847a-27166b111d31](https://gdi.berlin.de/geonetwork/srv/ger/catalog.search#/metadata/ea216e7d-77ca-3f96-847a-27166b111d31) and the technical description here [https://gdi.berlin.de/data/ua_forstbetriebskarte_2014/docs/Datenformatbeschreibung_05_04_forstbetriebskarte2014.pdf](https://gdi.berlin.de/data/ua_forstbetriebskarte_2014/docs/Datenformatbeschreibung_05_04_forstbetriebskarte2014.pdf)

Unfortunately, they did not link the age classes correctly at the end of the pdf. Therefore I have uploaded a copy of the html-file to the seminar’s data folder.

---

# 3. Your Tasks

## 3.1 Visualize the Data

- Visualize the data. Plots should include the CHMs as well as plots of the dominant tree species, the stand height and the stand age.

- Visually compare the plots of the lidar and vector data. Can you see patterns and structures in the lidar data that could be related to the vector data?

- Have a closer look at the attributes of the vector data. Would you classify all stands to be “pure”, meaning that the dominant tree species covers a large part of the stand?

**Hint:** You may of course make use of your last week’s script to calculate the CHM for the second plot.

## 3.2 Compare Heights

Compare the heights of the CHMs and the corresponding values from the vector data for several forest stands. Do they match?

## 3.3 Lidar Metrics

Different kind of lidar metrics were introduced in the lecture.

Looking into the functions of the lidr-package there are different ways to calculate these metrics. You may calculate these on the cloud, the pixel, the tree, the voxel and the point level.

This week, we will focus on the pixel and the tree level (additional) even though you might also try the other metrics.

An overview of the standard metrics can be found here: [https://github.com/r-lidar/lidR/wiki/stdmetrics](https://github.com/r-lidar/lidR/wiki/stdmetrics)

### 3.3.1 Lidar Metrics at the Pixel Level

Calculate lidar metrics at the pixel level for both las-files. You may use the standard metrics.

- Choose two different pixel resolutions (e.g. 5 and 20 m).

- Choose six different metrics and plot them (preferably: 1 plot with 6 subplots)

- Compare the results of the lidar data with the vector data on a visual basis. Can you see the boundaries of the forest stands also within the lidar data?

- Calculate statistics of the tree height (e.g. mean, standard deviation or use boxplots) from the lidar data for different forest stands (e.g. two differing dominant tree species and/or different stand age). What are your observations?

### 3.3.2 Additional: Lidar metrics at the tree level

- Calculate lidar metrics at the tree level for both lidar data sets. You may use the standard metrics (use the argument `geom = "convex"`).

- Visualize some of the metrics. Are the trees within on forest stand very similar?

For a better overview you may use a spatial subset of the data.

---
