---
title: "Week 8 - Intro to Lidar Data"
author: "Asad Waseem"
date: "15-08-2026"

format:
  html:
    toc: true
    toc-depth: 6
    toc-location: left
    code-fold: true
---

# Contents

This week you will get to know how to deal with lidar (also LIDAR, LiDAR) data in R. There is the package `lidR` which is dedicated for analyzing these data.

You will find an extensive tutorial describing the possibilities of the package regarding data analyses. Therefore, this is a great use case for you to get familiar working with tutorials to obtain the desired information.

You will learn how to

- Open the data
- Visualize the data
- Extract an digital terrain model and a digital surface model or canopy height model
- Identify tree tops
- Segment tree crowns

For those of you, who like to dig a bit deeper, there are some “additional” tasks.

---

# 1. Lidar data - Intro

In case you did not find time yet to have a look at the lecture, here is a short overview of lidar data: [https://www.youtube.com/watch?v=EYbhNSUnIdU](https://www.youtube.com/watch?v=EYbhNSUnIdU)

The detailed tutorial for the `lidR` package can be found here: [https://r-lidar.github.io/lidRbook/](https://r-lidar.github.io/lidRbook/)

---

# 2. The data

Berlin has an open data policy and therefore the data of the last lidar survey are freely available via FIS-Broker (Geo portal of Berlin). The amount of data is enormous and therefore, we may only focus on rather small patches. I have chosen a tile from Grunewald but you are free to download the data and choose another tile. (Hint: Be aware that the data amount is quite huge).

You may find the data here: [https://box.fu-berlin.de/s/xXJ5retoYgR64EY](https://box.fu-berlin.de/s/xXJ5retoYgR64EY)

---

# 3. Your Tasks

## 3.1 Reading the Data

- Read the lidar data.
- I recommend to use also a subset of the data because this makes it easier to see details of the lidar data, e.g. a subset of 100 m by 100 m might be a good size. 
For this purpose, useful functions are `ext(data)` and `clip_rectangle(data, xmin, ymin, xmax, ymax)`

## 3.2 Visualizing

Visualize the lidar data:

- Wimple 3D plot
- Voxel plot
- Additional: cross section

Please, be aware, that some of the examples in the tutorial only work if you already used functions that are explained only later in the tutorial. This is for instance the case for the overlay plots.

## 3.3 DTM

- Use one of the provided methods to derive a digital terrain model.
- Plot the data.
- Additional: Create a hillshade image.

## 3.4 DSM / CHM

- Derive a Digital Surface Model and plot it.
- Derive a Canopy Height Model and plot it.

For the latter you need to normalize the data. For this the DTM is required that you have just created. The normalization is the subtraction of the DTM from the original lidar heights. `data.normalized = data - dtm`

Thus, the terrain surface equals 0.

## 3.5 Tree Detection and Segmentation

“Individual tree detection (ITD) is the process of spatially locating trees and extracting height information. Individual tree segmentation (ITS) is the process of individually delineating detected trees.” (taken from the tutorial)

- Identify single trees.
- Segment the tree crowns.

In the case, you receive an error message like this “Error in st_crs.character(terra::crs(.x)) : invalid crs:”, you might define the correct coordinate system using following command: `crs(smoothed) <- 'EPSG:25833'`

Do the results look satisfactory?

---
