---
title: "Week 6 - Random Forest Classification"
author: "Asad Waseem"
date: "15-08-2026"

format:
  html:
    toc: true
    toc-depth: 6
    toc-location: left
    code-fold: true
---


# Contents

In this seminar you will learn how to use hyperspectral data in combination with random forest to create a tree species map from a hyperspectral HyMap image. 
The learned steps will include:
- Loading a hyperspectral image
- Visualizing a hyperspectral image and vegetation spectra extracted from pixels
- Conduct a supervised random forest classification using the original HyMap bands
- Conduct a supervised SVM classification using the PCA components as input
- Compare the accuracy of both data sets

The datasets applied in this tutorial are available here: [https://drive.google.com/file/d/1OkOcvNTDGR5PcBhress0pbwMP5wPqVui/view](https://drive.google.com/file/d/1OkOcvNTDGR5PcBhress0pbwMP5wPqVui/view)

---

# Datasets

In this tutorial we will make use of an airborne hyperspectral or imaging spectroscopy image that was collected with the HyMap sensor (HyMap_125bands_Karlsruhe2.tif). 
This dataset covers the spectral wavelengths regions between approximately 400 and 2400 nm. The HyMap image shows a forested area in the North of the German city Karlsruhe.

Additionally, a point-Shapefile is provided which contains sample points (reference positions) for 5 tree species (50 points per species, 250 in total) (tree_species_KA.shp). These reference positions were collected using visual interpretation of high-resolution images in combination with reference tree species maps provided by the local forest administration. These reference tree species maps are also provided as tif-files (Reference_information.tif; Reference_information2.tif). 
The latter might be used for comparison with the classification maps produced in the tutorial.

---

# Preparation

**Packages, working directory and reading the data.**

Open required packages `terra`, `random forest` and `e1071`.

```r
#install.packages("terra")
#install.packages("randomForest")
#install.packages("e1071")
# ...

library(terra)
library(randomForest)
library(e1071)
```

Set your working directory.

```r
setwd("P:\\ath\\to\your\datafolder")
```

---

# Step 1: Loading an visualizing the hyperspectral HyMap image and the reference dataset

After all packages are successfully installed, we will load the hyperspectral image and the shapefile containing the reference information.

```r
# load hyperspectral image
hym <- rast("HyMap_125bands_Karlsruhe2.tif")

# load reference data
ref <- vect("tree_species_KA.shp")
```

- **Homework Task 1:** Plot our hyperspectral image (hym_img) as a NIR false color composite. We will furthermore plot the reference data on top of the image using the species information to color-code each sample. The species information is stored in the attribute table of the shapefile in the column named “id”. In total, we consider five tree species, that we will introduce later on.

```r
# plot color infrared view of hyperspectral image
# your code

# add reference points
# your code
```

- **Homework task 2 Question:** Can you describe a difference between coniferous and broadleaved forest stands?

- **Homework task 3:** As next step, we will now extract the spectral values of the HyMap image at heach of the 250 reference point locations. So we will have 50 spectral signatures for each tree species. To do this we run:

```r
# extract spectral signatures at the reference data points
# your code
```

- **Homework task 4:** Now, we can have a look at the extracted spectral signature by running the plot command in a loop to plot all spectral signatures into the same plot window.

**Hint:** The x-axis is not optimal as we only use the band number instead of the wavelength itself. Because it is not really relevant for this seminar, we will leave this aside for this time.

**Hint2:** You might use the function par(new=T) within the loop to make the plotting a bit easier.

```r
# plot all spectra and color-code with species

# your code
```

In the plot, we used the species information to color-code the spectra, but as you can see this graph is quite chaotic, and it is hard to see where the spectra of one species ends and the spectra of another species start. All in all, there seems to be quite a heavy overlap between the spectral signatures of the five species. So let us try to make this plot a bit clearer by plotting the mean spectral signature of each species plus its standard deviations.

The species information stored in the Shapefile is coded with numbers. Below you can see which species belongs to which number code.

species: * id = 1 = Quercus robur/petreae (Common/Trembling Oak) * id = 2 = Pinus sylvestris (Pine) * id = 3 = Quercus rubra (Red Oak) * id = 4 = Fagus sylvatica (European beech) * id = 5 = Pseudotsuga menziesii (Douglas fir)

First, this information about the species will be attached to the dataframe containing the spectral signatures at the reference plot locations:

```r
hym.extract$species <- ref$id
```

Now we are ready to calculate the mean and standard deviation (sd) spectral signatures of each species.

```r
hym.extract.mean <- aggregate(hym.extract, hym.extract[,"species", drop=FALSE], mean)
hym.extract.sd <- aggregate(hym.extract, hym.extract[,"species", drop=FALSE], sd)
```

And now we plot the data.

```r
##################################
# plot mean + sd of each species
##################################

mycolors= c("forest green", "blue", "red", "orange", "black")
# plot the spectra for the first tree id and add the standard deviations

for (i in 1:5){
  plot(1:125, hym.extract.mean[i, 2:126], type="l", col=mycolors[i], ylim=c(0,6000), lwd=2, xlab= "band", ylab="reflectance*10000")
  # plot mean spectral signature + sd values
  lines(1:125, hym.extract.mean[i, 2:126]+hym.extract.sd[1,2:126], col=adjustcolor(mycolors[i], alpha.f=0.5), lty=2, lwd=2)
  # plot mean spectral signature - sd values
  lines(1:125, hym.extract.mean[i, 2:126]-hym.extract.sd[1, 2:126],  col=adjustcolor(mycolors[i], alpha.f=0.5), lty=2, lwd=2)
  par(new=T)
}

# add a legend indicating the species names
legend("topright", legend=c("Quercus robur", "Pinus sylvestris", "Quercus rubra", "Fagus sylvatica", "Pseudotsuga menziesii"), col=mycolors, lty=c(1,1,1,1,1))
```

- **Homework task 5 Question:** Which conclusions can you draw from the diagram about separating the tree species?

---

# Step 2: Tree species classification using the original HyMap bands

Now we are ready to start the classification. As you might already know, machine learning algorithms such as support vector machines, typically require a parameter tuning. That is, we try to identify the optimal settings of the classification algorithm by splitting the dataset into several parts and then use some of these parts to train the classifier (with a set of parameters) and then validate them with another part which has not been used during training. By repeatedly varying the parameters, we can find a combination of parameters, that performs exceptionally well.

In the case of SVM we can vary two parameters: gamma and cost. Gamma defines how flexible the so-called hyperplane is allowed to be. The hyperplane is basically the separation-“line” between the different classes in the feature space. On the other hand, cost describes how strongly the classifier punishes a wrongly classified sample. If cost and/or gamma is too high, there is a risk of overfitting - however, by applying datasplits during the grid search, overfitted models will lead to bad performances. By using an automated grid-search which varies the gamma and cost values within a user-defined range, it is possible to automatically search for a good gamma/cost combination in R. The corresponding code looks like this (this might take a while to run, as a lot of different models are examined here):

To tune the best svm model we use `tune()`

```r
gammas <-   2^(-8:5)
costs <- 2^(-5:8)
class.svm <- e1071::tune(svm,
              train.x = hym.extract[2:126],
              train.y = as.factor(hym.extract$species),
              type = "C-classification",
              kernel = "radial", 
              scale = TRUE,
              ranges = list(gamma = gammas, cost = costs),
              tunecontrol = tune.control(cross = 5)
              )
# Have a look at the information of the svm models:
summary(class.svm)
plot(class.svm)
```

In the next step we are saving the best combination of our model, i.e. the gamma and cost value of the best model. Then we parameterize the call of the function `svm()` accordingly.

```r
gamma <- class.svm$best.model$gamma
cost <- class.svm$best.model$cost

# train model
svm.best <- svm(hym.extract[2:126], as.factor(hym.extract$species), gamma = gamma, cost = cost, probability = TRUE, cross=5)
```

- **Homework task 6 Question:** This is the second function, where the argument cross=5 is used. What does it stand for and how does the concept behind basically work?

Now, let`s predict tree species for the entire image.

```r
hymap.class.svm <- terra::predict(hym, svm.best,
                  filename = "hymap_svm.tif",
                  overwrite = TRUE,type="prob"
                  #na.rm = T
)
```

- **Homework task 7:** Plot the result.

```r
# your code
```

Now, we are redoing the classification using random forest.

```r
#tunerf --> fits the best model by altering mtry and ntree
class.tunerf <- tuneRF(hym.extract[,2:116],
                  as.factor(hym.extract$species),
                  mtryStart = 5,
                  ntree = 1000,
                  importance=T,
                  doBest = T
                  )

# Let's have a look at the performance of the best model:
class.tunerf
```

- **Homework task 8:** What is your interpretation of the confusion matrix?

We use the two times the same function with a slightly different call.

- **Homework task 8 Question:** What is the difference of the two outputs? Plot the outputs.

**Hint:** Have a look at the help for `predict.randomforest()`:
[https://www.rdocumentation.org/packages/randomForest/versions/4.7-1.1/topics/predict.randomForest](https://www.rdocumentation.org/packages/randomForest/versions/4.7-1.1/topics/predict.randomForest)

```R
# call1
hymap.class.rf.call1 <- terra::predict(hym, class.tunerf,
                  filename = "hymap_svm_call1.tif",
                  overwrite = TRUE,type="prob"
                  #na.rm = T
)

# Call2:                  
hymap.class.rf.call2 <- terra::predict(hym, class.tunerf,
                  filename = "hymap_svm2_call2.tif",
                  overwrite = TRUE
                  #na.rm =T
)
```

- **Homework task 9:** What is the probability of the winner class, i.e. the class that was assigned to the pixels. Which areas show high probabilities, which low? 
**Hint:** Use the function `app()`

```r
# your code
```

- **Homework task 10:** Create from the “call1”-result the result of “call2”. Compare it to the result from the “predict”-function of the random forest model. 
**Hint:** Use the function `app()`

```r
max.class <- app(hymap.class.rf.call1, "which.max")
plot(max.class)
```

- **Homework task 11 Question:** What would we need to do to compare the performance of the SVM and RF classification?

---

