---
title: "Crash course week 3: Raster & Vector data"
author: "Asad Waseem"
date: "29-07-2026"
output:
   html_document:
     dev: svg
     fig_height: 4
     fig_width: 6
     number_sections: no
     theme: cerulean
     toc: yes
     toc_depth: 3
     toc_float: yes
---

# Visualization and further processing of raster and vector data in R

## Contents

1. Open and visualize raster data

2. Create a point vector dataset by importing a table

3. Read a polygon shapefile

4. Projections, transformations and subsetting

5. Intersection of raster and vector data

- Homework

---

# This week 

This week we will get basic knowledge how to work with vector data in R and how to intersect vector and raster data. You will work with three datasets: * You already know the elevation data. * Additionally you will work with a polygon dataset showing the municipalities in this area. * Moreover, you are going to work with a table that consists of meteorological data in the study area. You will learn how to create a point vector layer from this table.

You will learn how to work with vector data, e.g. how to have a look at the attribute table and how to select specific vector data. Moreover, you will see how to extract information from a raster layer for the vector data.

We will also have a look how “loops” can be implemented and you will try to create a loop yourself.

---

# Preparation

- Open a new R-file and save it. Fill in and run the requested R commands and comment as you like. Please, try to solve the exercises on your own before you have a look at the solution.

- Install the package terra if required and load it.

```r
#install.packages("terra")

library(terra)
```

- Set the working directory to the folder where today's data are located on your computer. Remember to use the right folder delimiter (`\\` or `/`)

```r
setwd('Y:\\Path\\To\\Your\\Workingdirectory')
```

---

# 1. Open and Visualise Raster Data

- Open the DEM from the last seminar n48_e008_1arc_v3.tif by using the function `rast()`.

```r
DEM <- rast("n48_e008_1arc_v3.tif")
```

- Plot the DEM using `plot()`

```r
plot(DEM, main="Digital Elevation Model (SRTM)", col=terrain.colors(25))
```

- Just for fun: Two further functions to visualize raster data such as DEMs. Use the functions `levelplot()` and `plot3D()` from the package `rasterVIS`. You will also need to install the raster package. With `plot3D()` a new window opens showing a 3D perspective of the DEM. You may change the view, zoom level etc. by using your mouse wheel. Unfortunately, `plot3D()` only works with a RasterLayer object (format of raster layers with the library (`raster()`) and not with a `SpatRaster` object as used with the `terra` library. Therefore we need to change the data type using the function `raster()`

```r
install.packages("rasterVis")
library(rasterVis)

install.packages("raster")
library(raster)

levelplot(DEM)

# Convert raster from "SpatRaster" (the terra format) to "RasterLayer" (the raster format; the package raster will not be maintained in # the future)
DEM.raster <- raster(DEM)
plot3D(DEM.raster)

# we may detach packages if we do not require them anymore
detach(package:rasterVis)
detach(package:raster)
```

- Just for fun II: Create an interactive display of spatial objects using the function `mapview()` from the package `mapview`. The data are displayed interactively in an html-widget. You may change the zoom level, the background data and may as well switch the displayed data set on and off. Also here we are working with `RasterLayer`.

```r
install.packages('mapview')
library(mapview)
library(raster)
mapview(raster(DEM))

# we may detach packages if we do not require them anymore
detach(package:mapview)
detach(package:raster)
```

---

# 2. Create a point Vector dataset by importing a table

- Open the file `stations_bawue_montly_temp.csv`.

**a.** What is the difference between the functions `read.csv()` and `read.csv2()?`

```r
# Both functions read tables that are saved in csv-format. They differ in the column separator and the decimal sign. 
    
# ``read.csv(file, header = TRUE, sep = ",", quote = "\"", dec = ".", fill = TRUE, comment.char = "", ...)``

# ``read.csv2(file, header = TRUE, sep = ";", quote = "\"", dec = ",", fill = TRUE, comment.char = "", ...)``
```

**b.** Which function is needed here?

```r
    temp <- read.csv2("stations_bawue_montly_temp.csv")
```

- Which kind of datatype are we dealing with?

```r
class(temp)
```

- Have a look at the table using the function `View()`

```r
View(temp)
```

- How does the structure of the table look like?

```r
str(temp)
```

- How can we access the longitude and latitude of the table? Save them to the objects x (longitude) and y (latitude).

```r
y <- temp$Lat
x <- temp$Lon
```

- How can we access the longitude and latitude of a specific station, e.g. the station with the ID 257.

```r
temp$Lat[temp$Station == 257]
```

- Plot the stations` locations. Do this by creating a scatter plot using the plot() function.

```r
plot(x,y)
   
#alternative
plot(temp$Lon, temp$Lat)
```

- We may create a point vector data layer using `vect()` and the arguments `geom=` and `crs=`.

```r
temp.point <- vect(temp, geom=c("Lon","Lat"), crs="+proj=longlat +datum=WGS84")
```

- Write the shapefile to disc using `writeVector()`.

```r
writeVector(temp.point,"temp_points.shp",layer = "points_temp", overwrite = TRUE)
```

- We may access the table of the dataset using e.g. `data.frame()` and `values()`.

```r
data.frame(temp.point)
values(temp.point)
```

- Display the point and raster data in one plot. First, plot the DEM. Afterwards use the argument `add=TRUE` for adding the points on top of the DEM. Use the arguments `pch`, `cex` and `col` to display the points in an appropriate manner.

```r
plot(DEM, main="Digital Elevation Model (DEM)", col=terrain.colors(25))
plot(temp.point, add=TRUE, pch=19, cex=1)
```

---

# 3. Read a Polygon Dataset

- Open and visualize the shapefile `AX_KommunalesGebiet.shp`.

```r
poly <- vect("AX_KommunalesGebiet.shp")
```

Which information is provided in the attribute table?

```r
values(poly)
```

- You may also have a look at the column names using the function `names()`

```r
names(values(poly))
```

- Visualize the shapefile `AX_KommunalesGebiet.shp`.

```r
plot(poly)
```

- Plot the fifth polygon.

```r
plot(poly[5,])
```

- Plot the polygon of “Geislingen”.

```r
plot(poly[poly$NAME=="Geislingen",])
```

---

4. Prijections, Transformations and Subsetting

- Try to display the DEM, the stations and the administrative boundaries in one plot. Remember to use the argument `add=TRUE` where appropriate. Does it work?

```r
plot(DEM, main="Digital Elevation Model (DEM)", col=terrain.colors(25))
plot(temp.point, add=TRUE, pch=19, cex=0.5)
plot(poly, add= TRUE)
```

- Have a look at the coordinate systems of the three datasets using the function `crs()`.

```r
crs(DEM)
crs(temp.point)
crs(poly)
```

- We may also test for equality of the coordinate systems.

```r
crs(DEM) == crs(poly)
```

- We need to make sure, that the coordinate systems are the same. There is no “on-the-fly” transformation of projections as you may know it from ArcMAP or QGIS. Reproject the polygon data to coordinate systems of the DEM or points, respectively, applying the function `project()`. This function exists in different packages. Depending on the order of loading the packages, you may be warned that a function is masked. In this case we need to specify the package: `terra::project()`. An alternative is to detach packages as we have done before.

```r
poly.latlon <- terra::project(poly,crs(DEM))
```

- Try again to plot the three datasets in onec plot. Hint: Order matters...

```r
plot(DEM, main="Digital Elevation Model (DEM)", col=terrain.colors(25))
plot(poly.latlon, add= TRUE)
plot(temp.point, add=TRUE, pch=19, cex=1.5, col="red")
```

The geographic extent of the data do not match. Create a geographic subset of the polygon data that matches the DEM using `crop()`. We used this function also last week. This week it is even easier as we can simply use the extent of another spatial dataset (here the DEM) to which the polygon data are clipped.

```r
poly.clip <- crop(poly.latlon, DEM)
```

- Plot the three datasets in one plot.

```r
plot(DEM, main="Digital Elevation Model (DEM)", col=terrain.colors(25))
plot(poly.clip, add= TRUE)
plot(temp.point, add=TRUE, pch=19, cex=1.5, col="red")
```

---

# 5. Intersection of Raster and Vector Data

Calculate the mean height of each municipality where a meteorological station exists.

**a.** What is happening here?

```r
poly.stations <- poly.clip[temp.point,]
plot(poly.stations)
```

**b.** Extract the values of the DEM for every polygon using the `extract()` function. Be patient, this may take a little while...

Even though `terra` seems to make this function a lot faster. So maybe only time for one espresso.

Have a look at the resulting object. Which data are included? Is it still a spatial data set? Have a look at the class of the variable.

```r
DEM.poly <- extract(DEM, poly.stations)
```

**c.** Use the function `extract()` to calculate the mean height. Which is the resulting class fo the created object?

```r
DEM.poly.mean <- extract(DEM, poly.stations, fun=mean)
```

**d.** The mean values are stored in a data.frame. If we would like to link the polygons and the mean values we need to join these data. We are doing this by adding a new column to the data table of the polygon data set.

```r
values(poly.stations) <- data.frame(values(poly.stations), hoehe=DEM.poly.mean[,2])

# check that new column was added to the data:
head(values(poly.stations))
```

**e.** Plot the height values in a diagram.

```r
poly.stations$hoehe
plot(poly.stations$hoehe)
```

**f.** Plot a map with all polygons lower than 700 m a.s.l displayed as black polygons, all the other polygons in red colour.

```r
plot(poly.stations[poly.stations$hoehe < 700,], col ="black")
plot(poly.stations[poly.stations$hoehe > 700,], col ="red", add=TRUE)
```

**g.** The following code shows how the polygons might be plotted in R illustrating the mean height. It is still not really a good map, but making nice maps in R need some testing and the use of more sophisticated functions such as provided by `ggplot`.

```r
plot(DEM, col=grey.colors(255), plg=list(x="topright", title="Height (m asl)"))
plot(poly.clip, border="white", add=T)
plot(poly.stations, "hoehe", breaks=c(0, 250, 500, 1000),add=T, plg=list(x="bottomright", title="Mean height (m asl)"))
```

Often, it might be more efficient to save the files to your disc and work with a GIS software for visualization. you may simply write the data to disc and open them in ArcGIS or QGIS.

```r
writeVector(poly.stations, "poly_hoehe", overwrite=TRUE)
```

---


# Homework 

## 1. Intersecting of Raster and Vecot data (Points)

We only have the temperature values for some weather stations that are scattered across the DEM. To create a spatially explicit raster of temperature, we will use the well-known relationship of air temperature and elevation which often show a high inverse correlation.

Hence, implement a linear regression between DEM heights and temperature values from January 2016 and use this model to perform a simplistic temperature interpolation. Follow the steps below.

- Extract DEM values at the point data coordinates as vector layer `dem.heights` using `extract()`.

- Save the temperature data from January 2016 named `temp_2016_1` to a numeric vector.

- Plot both numeric vectors in a scatterplot.

- Calculate the correlation and the coefficient of determination (r^2). Use the argument `use = "complete.obs". Why is this argument necessary?

- Detect the linear regression coefficients using the function `lm(y ~ x)`. Which vector is y, which vector is x? Where is gain and offset stored within the resulting object?

- Add the regression line to the scatterplot using `abline()`.

- Summary of the model

- The coefficients are saved in `lin_model$coefficients`. How to get the intercept and gain of the linear model?

- Interpolate the temperature data of our study area based on the linear model coefficients you just derived. Hint: It is not necessary to use functions such as `predict()`. You may apply simple algebra with raster data: e.g.if you would like to transform the height of the DEM from m to cm, simply calculate `height.in.cm <- DEM/100`

**Hint:** `predict()` will not work here as a function based on `lm()`. We will use the function `predict()` at a later stage…

- Plot your results in a map.

## 2. Intersection of Raster and Vector Data (Loop)

Usually, using functions such as `lapply()` is very efficient and is preferred over implementing loops. But because of the enormous amount of pixels it might be difficult to detect mean heights for all municipalities using the functions `extract()` and `lapply()` due to the computer`s specifications (limited working memory).

Therefore, alternatively to the exercise, we will implement a loop that is not very elegant but works.

That it is how a for `loop looks` like in R.


```r
# Create a vector with a sequence from 1 to 20 with stepsize 2.
input <- seq(1,20, 2)

print("This loop calculates the square of the 10 elements of the vector input")

# Initialize vec. There are several ways to initialize vectors. This is one...
vec <- vector(length=length(input))

for(i in 1:length(input)) {
  # i-th element of `input` squared into `i-th position of `vec`
  vec[i] <- input[i]*input[i]
  print(paste0("Loop ", i,": the square of ", input[i], " is ", vec[i]))
}

print(vec)
```

- Open the polygon dataset `AX_KommunalesGebiet.shp`

    - Of how many polygons i does the polygon dataset consist of?

- Create a loop (maybe test it first of all for 10 elements before performing the loop on the entire dataset)

    - Create an empty vector of where the mean heights of each polygon can be stored

    - Create a loop which loops over all polygons and, 

        i. Extracts DEM pixels for each polyogn
       ii. Calculates the mean height
      iii. stores the mean height of each polygon at position i of the result`s vector
      
- After executing the loop you need to join the vector to the polygon data set.

- Show the mean heights in a map (R or ArcMap/QGIS).